- name: Run NGINX reverse proxy container
  community.docker.docker_container:
    name: proxy
    image: nazimbz/tp-devops-simple-api-httpd:latest
    restart_policy: always
    recreate: true
    pull: true
    ports:
      - "80:80"
    networks:
      - name: my-network
    state: started
