- name: Run PostgreSQL container
  community.docker.docker_container:
    name: mydb
    image: nazimbz/tp-devops-simple-api-database:latest
    restart_policy: always
    recreate: true
    pull: true
    env:
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: db
    networks:
      - name: my-network
    state: started
